### ISSUE TITLE
Common check: module names in PascalCase

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#103]
Write a common check that is going to check module names. They should always be written in `PascalCase`.

See `lib/elixir_analyzer/exercise_test/common_checks.ex` and existing common checks for implementation details, e.g. https://github.com/exercism/elixir-analyzer/blob/e39b2cbe3f0565ff0b8f5ff6e3ccbf4826337479/lib/elixir_analyzer/exercise_test/common_checks/function_names.ex

Use Credo's implementation of this check as inspiration: https://github.com/rrrene/credo/blob/master/lib/credo/check/readability/module_names.ex

**Comment by neenjaw** [comment]
@jiegillet has completed this issue, awaiting merge
