### ISSUE TITLE
Common check: avoid unless with else

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#105]
Write a common check that is going to check for usages of `unless/else` and prompt students to rewrite it with `if/else`.

See Credo's comment about it for a nice explanation :) 

>      The reason for this is not a technical but a human one. The `else` in this
>      case will be executed when the condition is met, which is the opposite of
>      what the wording seems to apply.

See `lib/elixir_analyzer/exercise_test/common_checks.ex` and existing common checks for implementation details, e.g. https://github.com/exercism/elixir-analyzer/blob/e39b2cbe3f0565ff0b8f5ff6e3ccbf4826337479/lib/elixir_analyzer/exercise_test/common_checks/function_names.ex

Use Credo's implementation of this check as inspiration: https://github.com/rrrene/credo/blob/master/lib/credo/check/refactor/unless_with_else.ex

**Comment by f-francine** [comment]
If it is ok, I would like to work on this issue :)

**Comment by neenjaw** [comment]
Do you need anything to get started? Just shout if you get stuck

**Comment by neenjaw** [comment]
Also feel free to open a draft PR with partial work to get feedback along the way

**Comment by f-francine** [comment]
Thanks! I confess that I'm not really sure about how to get started. I'm pretty new to elixir and open source contributions, but my plan is to see how the unless-with-else analyzer is implemented in credo, and base myself on it.

**Comment by neenjaw** [comment]
So just because I don't know where you're at with stuff, here's the primer for the open source side:
1) Fork the repo (which I can see you've already done) 
2) clone it to your local `git clone <your fork>`
3) create a new branch for your feature (this issue) `git checkout -b <your feature>`
4) push it to github `git push --set-upstream origin <your feature>`
5) open a draft PR to this repo from your repo ([this link](https://github.com/exercism/elixir-analyzer/compare/main...f-francine:main))

I'll add a follow up comment with some tech pointers to help you get started on your code for this feature too

**Comment by f-francine** [comment]
Thanks! I've already created the branch and opened a draft pull request :)

**Comment by neenjaw** [comment]
Ok here are the things things I think need to be some (some points are a little general, so if you need any clarification please ask).

- [x] create a file to contain the logic for your feature (you've already done this in your draft PR
- [ ] create a comment entry in `constants.ex`
  - [ ] later, we'll repeat this PR process in another repo `website-copy` to add the comment text that students will see there
- [ ] In `ElixirAnalyzer.ExerciseTest.CommonChecks.UnlessWithElse`
  - [ ] create a `run/1` function which has the same signature as the run function in `ElixirAnalyzer.ExerciseTest.CommonChecks.FunctionNames`
  - [ ] call run from `ElixirAnalyzer.ExerciseTest.CommonChecks` with the ast
  - [ ] in `UnlessWithElse` Use `Macro.prewalk` to traverse the ast
    - [ ] you'll need to write a traverse function that functions similarly to the Credo example
  - [ ] return a list of  `%Comment{}` structs with the errors if there are any

**Comment by neenjaw** [comment]
For testing it you will have to write a test file to complement your added feature :)

**Comment by jlirochon** [comment]
Can I work on this one ?

**Comment by angelikatyborska** [comment]
@jlirochon How is it going? Do you need any help?

**Comment by jlirochon** [comment]
Hey @angelikatyborska thanks for asking !

It's just that I was not working on it until tonight 😅 

I submitted #220 if you want to look at it.
