### ISSUE TITLE
`newsletter` - confusing suggestions

### ISSUE THREAD

**Issue by michallepicki** [exercism/elixir-analyzer#136]
![image](https://user-images.githubusercontent.com/4972756/132063640-11a452c7-7399-4681-b947-7035a040a6e0.png)

I tried to follow the exercise instructions to the word, including hints, but there are suggestions anyway and they are a bit confusing:

1. The first suggestion says not to return `:ok` explicitly, while my function doesn't do that explicitly (it's just because that's what Enum.each does)
2. The second suggestion says to re-use functions, and I am guessing that's because I didn't close the log file. Exercise didn't really instruct to do that... And files get cleaned up automatically when process exits. In fact, with current Elixir's `File.read!/1` implementation, that function call also leaves a file that will be closed only after process exits. So the log file should be closed "manually" while emails file will get closed automatically?

**Comment by michallepicki** [comment]
About 2. - I re-visited the instructions it looks like I'm wrong:
> Now that you have all of the building blocks of the email sending procedure, you need to combine them together in a single function.

**Comment by angelikatyborska** [comment]
I agree that the instructions aren't clear enough about this. Would this help https://github.com/exercism/elixir/pull/872 ?

> with current Elixir's File.read!/1 implementation, that function call also leaves a file that will be closed only after process exits

Are we talking here about the process that is spawned by `File.read!`, or the process that calls `File.read!`? I always thought that files opened with `File.read!` are closed as soon as the whole content is read, so before the function finished executing. Can you point me to some info about this? I wouldn't want this exercise to mislead people.

**Comment by michallepicki** [comment]
> Would this help exercism/elixir#872 ?
Sure, looks great!

> I always thought that files opened with File.read! are closed as soon as the whole content is read, so before the function finished executing.

I can check again. I checked and saw that after File.read! returned the string it read, there was still a linked process for that file and descriptor was open, until caller process was alive. I will check again, maybe it was a race. I don't see guarantees about closing immediately anywhere in docs

**Comment by michallepicki** [comment]
That was just me being confused like always, file is auto closed, just monitor link is left, not sure why. Some internal erlang weirdness.

Sorry and thanks for the sanity check!
