### ISSUE TITLE
`assert_call` doesn't see "through" nested function calls

### ISSUE THREAD

**Issue by michallepicki** [exercism/elixir-analyzer#137]
![image](https://user-images.githubusercontent.com/4972756/132067943-3551a7cb-054b-4346-8564-dcd0ffbc1f76.png)

I added a helper function to re-use code, and got a recommendation to re-use code in a different way.

I understand this is the current limitation of the macro-based approach. Not sure if it could be improved in general, or maybe just for this exercise.

Alternative approach would be to use tracing. Here I adapted a `FreelancerRates` test to check that function is re-used, and this approach works even if additional helper functions are introduced:

```elixir
    @tag task_id: 4
    test "calls apply_discount" do
      :erlang.trace(self(), true, [:call])
      :erlang.trace_pattern({FreelancerRates, :apply_discount, 2}, true, [:call_count])

      assert FreelancerRates.days_in_budget(1_600, 50, 0.0) == 4

      {:call_count, apply_discount_calls} = :erlang.trace_info({FreelancerRates, :apply_discount, 2}, :call_count)
      assert apply_discount_calls == 1

      :erlang.trace_pattern({FreelancerRates, :apply_discount, 2}, false, [:call_count])
      :erlang.trace(self(), false, [:call])
    end
```

**Comment by jiegillet** [comment]
You're right, we didn't consider helper functions. I think your solution is a valid one and the analysis should reflect that. 

Adding tests like the one you propose changes the message students receive from "Good job, but it could be better if you reuse functions" to "You must reuse functions, this is part of the specifications", and I don't think we should do that.

We could enhance `assert_call` to build some kind of tree that keeps track of functions calling other functions. Totally doable.
