### ISSUE TITLE
Bug -- `RPG.CharacterSheet` false-positive error

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-analyzer#139]
Essential-level error is raised despite meeting the requirements

![Screenshot from 2021-09-04 00-26-49](https://user-images.githubusercontent.com/8953691/132085209-c3ba1e3c-6bb9-4bcd-b0ed-203192d847f8.png)

**Comment by neenjaw** [comment]
I'm guessing the matcher isn't expecting the pipe operator to be wrapping the call to `IO.puts/1` and `IO.inspect/2`

**Comment by neenjaw** [comment]
Probably should be triaged by @jiegillet since he wrote that section of the feature form matcher

**Comment by jiegillet** [comment]
Oh no! 
Yes, you are probably right, I didn't think of the pipe operator. Hopefully an easy fix, I'll get on it tonight!

**Comment by angelikatyborska** [comment]
@neenjaw can you resubmit your solution and confirm it was fixed?
