### ISSUE TITLE
`informational` should be `informative`

### ISSUE THREAD

**Issue by iHiD** [exercism/elixir-analyzer#151]
There's no `informational` type. It should be `informative`: https://github.com/exercism/elixir-analyzer/search?q=informational

**Comment by jiegillet** [comment]
That looks like a typically stupid mistake @jiegillet couldn't stop making if he tried.
I'll fix it, and add compiler errors so that can't happen again!

**Comment by angelikatyborska** [comment]
@jiegillet your only mistake was to keep somebody else's (👀) code that had the same mistake 😇

**Comment by jiegillet** [comment]
I stopped myself from using `git blame` on this one ;)
And my statement still stands, it is most definitely something I would keep doing!
