### ISSUE TITLE
Report compilation warnings as actionable

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#165]
Dealing with compilation warnings is crucial for writing clean and maintainable Elixir code, and can be a teaching experience for new developers. However, it shouldn't be a blocker preventing people from submitting their solutions. For this reason, it doesn't belong in the test runner, but here.

Unfortunately that means we need to add a compilation step for the student's submission, which will slow down the analyzer runs.

**Comment by jiegillet** [comment]
I would love to work on this, it's been on my mind for a while. I don't have a good plan yet, though.

> Unfortunately that means we need to add a compilation step for the student's submission, which will slow down the analyzer runs.

Can we quantify this somehow? I have never used benchmarks with Elixir.

**Comment by angelikatyborska** [comment]
The go to solution for benchmarking in Elixir is https://hex.pm/packages/benchee

All you need to have is a few different functions that you want to compare. Then you run them for a few thousand or hundred thousand times and Benchee prints the stats for you.
