### ISSUE TITLE
Handle common problems in `wine-cellar`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#172]
After browsing a few community solutions I only see one problem here so far. I also had it in my both mentoring sessions for this exercise 🤔 

## Problem 1: not using `Keyword.get_values` for filtering by color

`Keyword.get_values` is by far the shortest and easiest way to fulfill the requirement of filtering by color.

It should be favored over other approaches, also to encourage exploration of the standard library. It's already included in the hints.

Recursive approach
```elixir
 def filter(cellar, color, opts \\ []) do
    cellar
    |> filter_by_color(color)
    |> optional_filter_by_year(Keyword.get(opts, :year))
    |> optional_filter_by_country(Keyword.get(opts, :country))
  end

  defp filter_by_color([], _), do: []
  defp(filter_by_color([{color, wine} | tail], color)) do
    [wine | filter_by_color(tail, color)]
  end

  defp filter_by_color([{_, _} | tail], color) do
    filter_by_color(tail, color)
  end
```

List comprehensions
```elixir
  def filter(cellar, color, opts \\ []) do
    wines = 
      for {^color, wine} <- cellar do
        wine
      end
    opts
    |> Enum.reduce(wines, fn
      {:year, year}, wines -> filter_by_year(wines, year)
      {:country, country}, wines -> filter_by_country(wines, country)
    end)
  end
```

**Comment by jiegillet** [comment]
That's a simple `assert_call`: calling function `filter` and called function `Keyword.get_values`.
I was guilty myself of not knowing about Keyword.get_values` 😅

**Comment by Br1ght0ne** [comment]
Hey, I used `Keyword.get_values` in [my solution](https://exercism.org/mentoring/external_requests/a7057b923d194b08beddcd5c32874350)! Glad to know it's a preferred solution. I'll handle this issue.
