### ISSUE TITLE
Update concept exercise `boutique-inventory` expectation to use Enum.into

### ISSUE THREAD

**Issue by fmmatheus** [exercism/elixir-analyzer#199]
Original thread: https://github.com/exercism/elixir-analyzer/pull/194

### Description

Update `increase_quantity ` function expectation (code analysis, hints and examples) on `boutique-inventory` concept exercise to use `Enum.into/3` instead of `Enum.map` + `Enum.into/1`.

### Motivation

@angelikatyborska found out by searching on community answers that most users are using `Enum.map` + `Enum.into/1` on `increase_quantity` solution (which still correct), but the same can be achieved by only using `Enum.into/3` which is a more concise and elegant solution for a concept exercise teaching about `Enum` usage.

**Comment by homeopathicdoctor** [comment]
[https://drtariqkhan.com/](url)

**Comment by AlenMorgan** [comment]
I think this [ Add check for increase_quantity function on boutique-inventory exercise ]

**Comment by angelikatyborska** [comment]
This issue was already resolved a while ago in: https://github.com/exercism/elixir-analyzer/pull/203
