### ISSUE TITLE
`high-score` analysis unclear about having to use the module attribute in two places

### ISSUE THREAD

**Issue by ynfle** [exercism/elixir-analyzer#216]
It seems that there is incorrect detection of a module constant in the `high-score` exercise

<img width="1280" alt="Screen Shot 2021-11-07 at 3 33 01 AM" src="https://user-images.githubusercontent.com/23086821/140628997-9ca19015-0423-46b3-bb59-263b6a756d39.png">

**Comment by angelikatyborska** [comment]
The comment is confusing if you only use the module attribute in one of the two required places (`add_player`, `reset_score`). Either the comment needs to be rephrased or the two checks need to have separate comments.

**Comment by ynfle** [comment]
Ahhhh. Makes sense.

Thanks

**Comment by jiegillet** [comment]
I'll vote for rephrasing the comment. In fact, I'll go do it now.

**Comment by jiegillet** [comment]
Turns out, there is actually 2 checks already, but this one doesn't the specific function for some reason...
