### ISSUE TITLE
Common check: function capture instead of defining a new anonymous function

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#218]
Add a common check for all exercises that will detect creating unnecessary anonymous functions and suggest capturing an existing function instead.

An anonymous function is unnecessary when the only operation in its body is calling another function with exactly the same arguments in the same order.

Make sure to detect both ways of creating an anonymous function, with the capture operator `&` and with `fn`.

```elixir
# example 1
# unnecessary new anonymous function
fn n, acc -> n + acc end
# could be
&Kernel.+/2

# example 2
# unnecessary new anonymous function
& String.upcase(&1)
# could be
&String.upcase/1
```

See https://github.com/exercism/elixir-analyzer/pull/217#discussion_r744255070
See the existing analysis done for Top Secret that has this check already, but it's exercise-specific 
    - https://github.com/exercism/elixir-analyzer/blob/main/lib/elixir_analyzer/test_suite/top_secret.ex#L23-L31
	- https://github.com/exercism/website-copy/blob/main/analyzer-comments/elixir/top-secret/function_capture.md

For clarity, here are examples when the new anonymous function is necessary:
```elixir
# necessary because of swapped argument order
fn n, acc -> div(acc, n) end

# necessary because of an extra argument
& IO.inspect(&1, charlists: :as_lists)
```

**Comment by jiegillet** [comment]
I'll take this one :)

**Comment by jiegillet** [comment]
I ran into one exception from `chessboard`.

```elixir
      def files do
        Enum.map(file_range(), &<<&1>>)
      end 
```
I couldn't find a way to rewrite that, so I'll have to hardcode a list of exceptions. Now I wonder if there are more and how to find them...

**Comment by jiegillet** [comment]
Note: fix later

Concept exercise:

https://github.com/exercism/elixir/blob/9adc180d9cb6c6697847c0502bc029d95e1ffab5/exercises/concept/rpn-calculator-inspection/.meta/exemplar.ex#L22

Practice exercise:

```elixir
[
  {"difference-of-squares", %{actual: "fn x, acc -> +(x, acc) end", expected: "&+/2"}},
  {"rna-transcription", %{actual: "&transcribe(&1)", expected: "&transcribe/1"}},
  {"largest-series-product", %{actual: "fn x, acc -> *(x, acc) end", expected: "&*/2"}},
  {"list-ops", %{actual: "&append(&1, &2)", expected: "&append/2"}},
  {"transpose",
   %{
     actual: "fn x -> String.to_charlist(x) end",
     expected: "&String.to_charlist/1"
   }},
  {"grep", %{actual: "fn a, b -> |||(a, b) end", expected: "&|||/2"}},
  {"pythagorean-triplet", %{actual: "&+(&1, &2)", expected: "&+/2"}},
  {"acronym", %{actual: "fn x -> String.first(x) end", expected: "&String.first/1"}},
  {"ocr-numbers", %{actual: "fn a -> String.length(a) end", expected: "&String.length/1"}}
]
```
