### ISSUE TITLE
Dockerhub push issue

### ISSUE THREAD

**Issue by neenjaw** [exercism/elixir-analyzer#22]
I just added the dockerhub.yml files, but the GHA failed (https://github.com/exercism/elixir-analyzer/runs/1119816649).  It doesn't differ from the run for exercism/elixir-test-runner, but that one passed.  Does this need to have some permissions set?

@ErikSchierboom did I miss something?

**Comment by ErikSchierboom** [comment]
> Does this need to have some permissions set?

I don't think so. Looking at the logs, it looks like the _building_ of the image was actually failing. It might be some temporary issue. I've just re-run the job manually and it now succeeds: https://github.com/exercism/elixir-analyzer/runs/1121750590

**Comment by neenjaw** [comment]
¯\_(ツ)_/¯
