### ISSUE TITLE
False positive in basics

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/elixir-analyzer#267]
![image](https://user-images.githubusercontent.com/1964376/158028696-47d91d9c-3831-4a34-b193-ff55f29e1dcb.png)

I probably should have used different syntax (without the `Lasagna.` prefix?), but I am pretty sure I used the function.

**Comment by angelikatyborska** [comment]
Damn 😞

> (without the Lasagna. prefix?)

Yes.

There are other affected exercises: guessing game, chessboard, high school sweetheart... Basically anything that calls`assert_call` with a local function name without a module name specified in `called_fn`. Specifying the module name in `called_fn` will make it work (not return comments) for local function calls with and without a module name, which would be a quick fix. But a better, longer fix, would be to mention that you don't need the module name when referring to the function in those cases.

**Comment by jiegillet** [comment]
I can’t believe this never came up before :)

I would propose
1. Making assert_call accept the module prefix even if none is specified 
2. Adding a common check: you don’t need to use the module prefix in the module itself. 

Shouldn’t be too hard…

**Comment by SleeplessByte** [comment]
FYI the reason I prefixed it with the module name is because in the introduction and instructions, all calls are prefixed. It worked, so I thought I did the right thing 😄
