### ISSUE TITLE
TakeANumberDeluxe always returns compliation warnings about unknown module State

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#276]
Note this analysis result for the exemplar solution:
![Screenshot 2022-04-11 at 21-10-42 Exercism](https://user-images.githubusercontent.com/7852553/162812512-e6d89f7b-47c7-42b3-9653-a35c4e522b2e.png)

**Comment by angelikatyborska** [comment]
I think the solution has to be to prepend/append editor files to the code before it gets compiled for the sake of compilation warnings 🤔 

This doesn't affect dancing-dots because there the other module only gets used for type definitions.

**Comment by angelikatyborska** [comment]
As a quick fix, we think we could also use `use ElixirAnalyzer.ExerciseTest, suppress_tests: [Constants.solution_compiler_warnings()]` on this exercise. Not ideal, but better than false-positives.

**Comment by angelikatyborska** [comment]
> For the compiler warning, we might have to switch to Kernel.ParallelCompiler.compile/2 instead.

It does sound like what we need: "Those files are compiled in parallel and can automatically detect dependencies between them.".

I think there are multiple topics here, multiple levels of complexity...
1. Support more than 1 solution file, read from the config. All of the analyzer checks should run on all of them because all of them must be edited by the student. So far we don't have such an exercise, but dancing-dots could have been like this (you need to write 3 modules).
2. Support editor files. This I think matters mostly for compilation warnings. Editor files aren't supposed to be edited by students, so any analyzer comments coming from them would be our fault. But they need to be compiled to correctly report compilation warnings for solution files.
3. Support arbitrary files. This one is the trickiest but could also simultaneously cover the other two cases. There are definitely analyzer checks that would be great to run on arbitrary files: variable naming, compilation warnings, unless/else etc. Mostly the common checks, not exercise specific checks that make a lot of assumptions about the solution. But should we tell apart solution files and editor files from all the `lib/.*` files and give them extra treatment? E.g. to prevent reporting compilation errors from editor files that we ourselves wrote. 

> I've always thought it would be best for the analyzer to read and concat all of the .ex files in lib into one instead of just reading the solution file.

For the compilation warnings, we need to retain file names and line numbers. For everything else, it might work. I guess we should just try something and see which problems arise 🙃

**Comment by jiegillet** [comment]
I want to signal that I've been working on this (it's missing some tests), but I'm blocked by #284 (`elixir.solution.function_annotation_order` is triggered when all files are concatenated) and #286 (the exemplars update part). 
I'll switch on working on #284 for now.

**Comment by angelikatyborska** [comment]
@jiegillet You should be unblocked now, sorry for the long wait!

**Comment by jiegillet** [comment]
Thank you, no need to apologize :)
