### ISSUE TITLE
New macro for checking that snippet Y is nested somewhere within snippet X

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#29]
For the new concept exercises for v3, we wrote a lot of notes about the analyzer that say something like "verify that function Y calls function X", e.g.

https://github.com/exercism/v3/blob/d9a84126c0e7aee415804d20d58d58fd1d31f915/languages/elixir/exercises/concept/lasagna/.meta/design.md#L42

https://github.com/exercism/v3/blob/6576904cbe3ddae26b23a418da8e012162980c4a/languages/elixir/exercises/concept/boutique-inventory/.meta/design.md#L29-L34

https://github.com/exercism/v3/blob/6576904cbe3ddae26b23a418da8e012162980c4a/languages/elixir/exercises/concept/high-school-sweetheart/.meta/design.md#L27-L33

This is almost impossible to achieve with the current `feature + form` macros. This is because there could be any number of lines before or after the inner code snippet. Let's say I wanted to check that the function `foo/1` uses `String.trim(). Those are all valid solutions that would pass the tests, and should also pass the analyzer:

```elixir
def foo(x) do
  String.trim(x)
end

def foo(x) do
  1
  String.trim(x)
end

def foo(x) do
  1
  2
  String.trim(x)
end

def foo(x) do
  1
  2
  3
  String.trim(x)
end

def foo(x) do
  1
  y = String.trim(x)
  2
  y
end

# and so on...
```

We cannot use `feature + form` to simply find a `String.trim(x)` anywhere in the solution because depending on the exercise, that might be missing the point (e.g. for this one: https://github.com/exercism/v3/blob/6576904cbe3ddae26b23a418da8e012162980c4a/languages/elixir/exercises/concept/boutique-inventory/.meta/design.md#L33-L34 you _don't_ want to find `Enum.reduce` in the function that was supposed to use `Enum.filter`.

It looks like we need something new for this use case.

**Comment by neenjaw** [comment]
I think first I would like to start my experimenting with a new macro that looks for a function call inside of some other function.  Something that would look like:

```elixir
ensure_call "function x calls function y" do
  calling_function ModuleA.x/3
  called_function ModuleB.y/2
end
```

This would perform some sort of pre-order search of the AST which would only succeed if it found that function call inside of the calling function.

I think this would also result in a pattern that we could then apply to `feature + form` to add a qualifier `found_in` which we could use to limit a search to a particular function.

**Comment by angelikatyborska** [comment]
I think as long as `called_function` allows for multiple options, that should be enough. But we do need to account for different possible arities (e.g. `String.trim/1`, `String.trim/2`) and maybe sometimes for groups of interchangable functions (e.g. `Enum.fiter` and `Enum.drop`).

**Comment by neenjaw** [comment]
I like those suggestions, I think they could be accomodated quite easily.
 would providing a list of functions work to satisfy that?

**Comment by angelikatyborska** [comment]
Yes, I think providing a list of functions will be most straight-forward and flexible.

**Comment by angelikatyborska** [comment]
I consider this feature request satisfied by https://github.com/exercism/elixir-analyzer/pull/49 :)
