### ISSUE TITLE
Readme instructions for rpn-calculator-inspection

### ISSUE THREAD

**Issue by jayber** [exercism/elixir-analyzer#315]
I'm just doing the exercise on Task and this sentence is in the readme:
> Any task started with Task.async/1 should be awaited because it will send a message to the calling process.

I'm not certain, but isn't this sentence missing a "not"?
> Any task started with Task.async/1 should be awaited because it will ***not*** send a message to the calling process.

Ie the reason this should be awaited is that it won't send a message, and therefore this is the only way to get its result?

I hope I haven't misunderstood again.

**Comment by jayber** [comment]
I'll submit a PR if I haven't

**Comment by jayber** [comment]
Dammit, I think I've got this wrong... again. So sorry. Closing

**Comment by angelikatyborska** [comment]
No worries! The sentence is correct, as you already realized. Let me expand on it: any process started with `Task.async/1` will send a message back to the process that called it. That's how tasks work. If you call `Task.await/2` on that task, it will wait for that message - when it arrives, it will know that the task has finished. However, if you don't call `Task.await/2`, then that message will be stuck in the calling process' mailbox indefinitely. If this happens for millions (or maybe billions, don't quote me on this number 🙂 ) of messages, you might start getting memory usage problems in your application.
