### ISSUE TITLE
Elixir track: @doc first, @spec next to function

### ISSUE THREAD

**Issue by georgevanuta** [exercism/elixir-analyzer#335]
# The exercise is [sieve](https://exercism.org/tracks/elixir/exercises/sieve).
## Got this comment on my solution:
<img src="https://user-images.githubusercontent.com/74255152/193430744-1f908dd9-2b73-4d37-a4c5-d3b6f73bcfd8.png" width="450" >\
## But the `@doc` already is before the `@spec` in my code:
<img src="https://user-images.githubusercontent.com/74255152/193431060-7bd11132-5ddf-4422-bb9d-776a5815d07e.png" width="450" >\
<img src="https://user-images.githubusercontent.com/74255152/193431062-7fe7fceb-ff0c-4ae8-8b4f-e39c000613b0.png" width="450" >\

**Comment by jiegillet** [comment]
Hi @georgevanuta, thanks for the feedback.
Yes, it a known bug (#318), basically the analyzer fires that comment every time a `@spec` or `@doc` are used with a private function.
We are working on it in (#332), I'll close this issue, but feel free to follow the others.
