### ISSUE TITLE
use of bitwise operators in the 'Secrets' exercise

### ISSUE THREAD

**Issue by matari-dev** [exercism/elixir-analyzer#365]
_Please refer to my iterations for this exercise_  
_I am using Elixir 1.9.1 on my local machine_

- **iteration 1**  
I pass exercise but I am warned that `use Bitwise` is deprecated so  
I use the recommended `import Bitwise`  
- **iteration 2**  
I pass exercise but I am warned that `import Bitwise` is unused even though  
I am using it on lines 30 & 36 but  
I try removing `import Bitwise`  
- **iteration 3**  
Exercism is happy (_even though it shouldn't be because I didn't `import Bitwise`?_).  
There are no warnings and I pass the exercise but  
running the tests locally on my machine I get 
tests that fail if the tests involve using the functions `secret_and` and `secret_xor`

**Comment by angelikatyborska** [comment]
Hi! Yes, there has been a significant change in how the `Bitwise` module behaves between Elixir 1.9 and Elixir 1.14 (current version). The test runner and analyzer on Exercism always run on the newest Elixir version. Locally, all exercises should work in Elixir versions 1.9 to 1.14.

Elixir 1.9 is pretty old (June 2019) and it would be better for your learning experience if you upgraded to the newest version. As soon as Elixir 1.15 gets released, we will shift the range of versions we validate the exercises against to 1.10-1.15. 

If you choose not to upgrade, I'm afraid you'll get some failing tests and weird analyzer output after submitting your exercises.

**Comment by matari-dev** [comment]
Thank you!  
I upgraded to the latest available version of Elixir (via their website¹) for Ubuntu (_i.e. version 1.13.4_) and can confirm that I can pass without even having to include `import Bitwise` on my local machine.  

That said, I would like to know where I can make a request that a note be added in Elixir's track documentation for `Installing Elixir locally`² stating that Exercism users should try installing the latest version and/or what is the oldest version that is still okay to use.  

I say this because currently, if users follow the instructions provided there (_as I did_) they may get version that is older than what is recommended.

1. https://www.erlang-solutions.com/downloads/
2. https://exercism.org/docs/tracks/elixir/installation

**Comment by angelikatyborska** [comment]
That's a good point, we don't mention anywhere what those versions actually are... I opened a PR: https://github.com/exercism/elixir/pull/1279

**Comment by matari-dev** [comment]
Awesome, thank you @angelikatyborska !  🙇‍♂️
