### ISSUE TITLE
Extend `CommonChecks.DebugFunctions` to look for calls to `dbg`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#368]
- Extend the module `ElixirAnalyzer.ExerciseTest.CommonChecks.DebugFunctions` to also find calls to `dbg()`
- Add tests
- Update comment https://github.com/exercism/website-copy/blob/main/analyzer-comments/elixir/solution/debug_functions.md

**Comment by elfenlaid** [comment]
Replying to https://mas.to/@angelikatyborska/110878322509896396

I'd like to give it a try, if you don't mind 🙏

**Comment by angelikatyborska** [comment]
@elfenlaid Awesome! Ping me here if you have any questions.

**Comment by angelikatyborska** [comment]
Done and deployed 🙌 

![Screenshot 2023-08-15 at 15 56 22](https://github.com/exercism/elixir-analyzer/assets/7852553/5f2f329c-d8c1-452c-87e1-5578a5ea7f30)

**Comment by elfenlaid** [comment]
Awesome, thanks 🙇
