### ISSUE TITLE
Elixir Analyzer is flagging Essential feedback for "Strain" that isn't relevant

### ISSUE THREAD

**Issue by opie4624** [exercism/elixir-analyzer#387]
See my Iteration 2: https://exercism.org/tracks/elixir/exercises/strain/solutions/opie4624

Analyzer says:

> As the instructions mention, you should implement keep/2 and discard/2 without the use of Enum.filter/2, Enum.reject/2. Also avoid their Stream equivalents and list comprehensions.

**Comment by angelikatyborska** [comment]
The analyzer comment is correct - your solution uses list comprehensions (`for`)
