### ISSUE TITLE
Elixir `german-sysadmin` exercise recommends shorthand Unicode syntax when it is already being used.

### ISSUE THREAD

**Issue by Kaylebor** [exercism/elixir-analyzer#388]
On the automated suggestions for this Elixir exercise, despite my submission already following the suggestion, the bot tells me to use the `?ä` syntax.

Exercise: https://exercism.org/tracks/elixir/exercises/german-sysadmin
Code:
```elixir
defmodule Username do
  @spec sanitize(charlist) :: charlist
  def sanitize(username) do
    username
    |> Enum.filter(&(&1 in ~c"äöüßabcdefghijklmnopqrstuvwxyz_"))
    |> Enum.reduce([], fn char, list ->
      case char do
        ?ä -> [?e, ?a | list]
        ?ö -> [?e, ?o | list]
        ?ü -> [?e, ?u | list]
        ?ß -> [?s, ?s | list]
        c -> [c | list]
      end
    end)
    |> Enum.reverse()
  end
end
```

**Comment by angelikatyborska** [comment]
Hi! Thanks for the report. This issue is related to https://github.com/exercism/elixir-analyzer/issues/384, the wrong feedback is given for the same reasons. I need to tackle this soon...

**Comment by Kaylebor** [comment]
Oh, I should have looked into open issues more. I'll just close this one then.
