### ISSUE TITLE
Newsletter in Elixir track has incorrect automated feedback 

### ISSUE THREAD

**Issue by octowombat** [exercism/elixir-analyzer#398]
In submitting to the Elixir track my solution to the Newsletter exercise, I received the following automated feedback. I don't understand why it marks as `Essential` a code suggestion that my submitted code already has.

<img width="1396" alt="Screenshot 2023-10-12 at 08 12 55" src="https://github.com/exercism/elixir-analyzer/assets/81933726/f3c2913f-8618-4e6b-88b1-f87fbd870858">

**Comment by jiegillet** [comment]
Hello @octowombat, thanks for opening the issue.
Yup, it looks like a bug, I think the analyzer did not expect the `when is_binary(path)`, it should be fixable.

On an unrelated note, @angelikatyborska do the comments not get their headers removed anymore? The `#open_log uses options :write` should not be there.

**Comment by octowombat** [comment]
Thanks @jiegillet for the fast response. Should I wait or attempt a fix myself?

**Comment by jiegillet** [comment]
You are very welcome to try it yourself!
The main file to change [is here](https://github.com/exercism/elixir-analyzer/blob/main/lib/elixir_analyzer/test_suite/newsletter.ex), the simple fix would be to add more variants like 

```elixir
    form do
      def open_log(_ignore) when _ignore do
        _block_includes do
          File.open(_ignore, [:write])
        end
      end
    end
```

We would also need [new tests in here](https://github.com/exercism/elixir-analyzer/blob/main/test/elixir_analyzer/test_suite/newsletter_test.exs).

I'll assign the issue to you, let me know if you need more guidance :)

**Comment by octowombat** [comment]
@jiegillet Thanks!

**Comment by octowombat** [comment]
Apart from the above query, I have the tests and fix ready to push as a PR.

**Comment by octowombat** [comment]
Some more details on the test failure: Looking into failing test
```
test/elixir_analyzer_test.exs:63
     Assertion with == failed
     code:  assert Submission.to_json(analyzed_exercise) == String.trim(expected_output)
     left:  "{\"comments\":[{\"type\":\"essential\",\"comment\":\"elixir.general.file_not_found\",\"params\":{\"file_name\":\"two_fer.ex\",\"path\":\"test_data/two_fer/missing_file_solution/\"}}],\"summary\":\"Check the comments for things to fix. 🛠\"}"
     right: "{\"comments\":[{\"type\":\"essential\",\"params\":{\"file_name\":\"two_fer.ex\",\"path\":\"test_data/two_fer/missing_file_solution/\"},\"comment\":\"elixir.general.file_not_found\"}],\"summary\":\"Check the comments for things to fix. 🛠\"}"
     stacktrace:
       (ex_unit 1.15.2) lib/ex_unit/capture_log.ex:113: ExUnit.CaptureLog.with_log/2
       (ex_unit 1.15.2) lib/ex_unit/capture_log.ex:75: ExUnit.CaptureLog.capture_log/2
       test/elixir_analyzer_test.exs:67: (test)
```

and grabbing the single comment in the list, thus;
```
comment = %{
  type: :essential,
  comment: "elixir.general.file_not_found",
  params: %{
    "file_name" => "two_fer.ex",
    "path" => "test_data/two_fer/missing_file_solution/"
  }
}
```

Then encoding that comment to JSON gives;
```
iex(2)> Jason.encode!(comment)
"{\"type\":\"essential\",\"comment\":\"elixir.general.file_not_found\",\"params\":{\"file_name\":\"two_fer.ex\",\"path\":\"test_data/two_fer/missing_file_solution/\"}}"
```

which shows the field `comment` as the second encoded field in the object/map but the expected encoding in the test has this field further on in the object/map.

**Comment by angelikatyborska** [comment]
> On an unrelated note, @angelikatyborska do the comments not get their headers removed anymore? The #open_log uses options :write should not be there.

Markdown syntax error. The comment needs to have a space after `#`.

**Comment by jiegillet** [comment]
Mmh, it smells of [this change in OTP26](https://www.erlang.org/blog/otp-26-highlights/#changed-ordering-of-atom-keys), the order of the maps is not guaranteed. It's definitely not related to this issue, I'll see if I can fix it.

**Comment by jiegillet** [comment]
I opened a PR #399

**Comment by jiegillet** [comment]
@octowombat you should be able to resume now.

**Comment by octowombat** [comment]
I have pulled in the update from the upstream repo but I am still getting 2 failures for the tests on line 26 and 160.  I will investigate further as it is the same kind of error, i.e. a mismatch of the list of warnings.

**Comment by octowombat** [comment]
The test on line 26 is strange since the expected list of comments has 11 elements whereas the resultant list within the `analyzed_exercise` `Submission` struct returned to the test has only 9 elements.

**Comment by jiegillet** [comment]
I commented on the PR :)

**Comment by octowombat** [comment]
Thanks, I reverted the deletion with a comment and also commented upon the question about the other variants.
