### ISSUE TITLE
Elixir Lasagna "Reusing an already written function can help when writing maintainable code."

### ISSUE THREAD

**Issue by berkdenk** [exercism/elixir-analyzer#402]
Reuse existing functions:

    remaining_minutes_in_oven/1 can reuse expected_minutes_in_oven/0
    total_time_in_minutes/2 can reuse preparation_time_in_minutes/1

My Code:
defmodule Lasagna do
  def expected_minutes_in_oven() do
    40
  end
    
  def remaining_minutes_in_oven(x) do
    expected_minutes_in_oven()-x
  end

  def preparation_time_in_minutes(x) do
    x*2
  end

  def total_time_in_minutes(layer_number,minutes) do
    (2*layer_number)+minutes
  end
  def alarm do
    "Ding!"
  end
end

What is the wrong?

**Comment by angelikatyborska** [comment]
Hi! The problem is that your implementation of the function `total_time_in_minutes/2` does not call the function `preparation_time_in_minutes/1`, but it's supposed to.

**Comment by berkdenk** [comment]
I understand now.Thank you for your answer.
