### ISSUE TITLE
Elixir code analyzer is not recognizing default value using a constant variable.

### ISSUE THREAD

**Issue by KevinGenus** [exercism/elixir-analyzer#406]
Use a [default argument](https://elixir-lang.org/getting-started/modules-and-functions.html#default-arguments) in the add_player/3 function to handle a lack of initial score. Use the module attribute with the default initial score.

I'm new to Elixir, this worked as expected and defined, but analysis disagrees.

```
defmodule HighScore do
  @initial_score 0

  def new(), do: %{}

  def add_player(scores, name, score \\ @initial_score)
  when is_map(scores) and is_binary(name) do
    Map.put(scores, name, score)
  end
end
```

**Comment by jiegillet** [comment]
Hi @KevinGenus, thanks for opening the issue!

it is a bug of the analyzer, it doesn’t expect the `when` clause in your solution. 

It’s a fairly easy fix, would you be interested in opening a PR for it? I can provide more guidance if you are.

**Comment by youve** [comment]
I also got this suggestion, but I don't have a when clause in mine:

```elixir
  def add_player(scores, name, score \\ 0) do
    Map.put(scores, name, score)
  end
  ```
  
  > Recommended
> Use a default argument in the add_player/3 function to handle a lack of initial score. Use the module attribute with the default initial score.


The second sentence is a valid suggestion for my code, but the first is not.

**Comment by jiegillet** [comment]
@youve, in your case, I believe the relevant part of the suggestion is "Use the module attribute with the default initial score". Using a module attribute for defining constants is idiomatic Elixir.
