### ISSUE TITLE
In exercise `TwoFer`, a recommendation to use `String.t()` in the typespec is added, even if `String.t()` is used.

### ISSUE THREAD

**Issue by jelemux** [exercism/elixir-analyzer#413]
**My code:**

```elixir
defmodule TwoFer do
  @moduledoc """
  Provides ways to share cookies
  """

  @doc """
  Two-fer or 2-fer is short for two for one. One for you and one for me.
  """
  @spec two_fer(name :: String.t()) :: String.t()
  def two_fer(name \\ "you") when is_binary(name) do
    "One for #{name}, one for me."
  end
end
```

**Expectation:** The typespec is considered okay by the analyzer.

**Reality:** The following recommendation is given:

> Make sure that the typespec for two_fer/1 is correct. The function accepts one argument - a string, and returns one argument - also a string.
> 
> The right type for strings is [String.t()](https://hexdocs.pm/elixir/String.html#t:t/0).
> 
> > The types String.t() and binary() are equivalent to analysis tools. Although, for those reading the documentation, String.t() implies it is a UTF-8 encoded binary.
> 
> The [type string()](https://hexdocs.pm/elixir/typespecs.html#the-string-type) means a charlist, not an Elixir string.
> 
> > Elixir discourages the use of the string() type. The string() type refers to Erlang strings, which are known as "charlists" in Elixir. They do not refer to Elixir strings, which are UTF-8 encoded binaries.

**Comment by angelikatyborska** [comment]
Thank you! This should fix it: https://github.com/exercism/elixir-analyzer/pull/414
