### ISSUE TITLE
Write a basic `flatten-array` analysis

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#60]
The exercise `flatten-array` is meant to practice recursion and pattern-matching on lists. If it's solved using the `List` or `Enum` functions, it's just way too easy. Thus this exercise should use the same kind of analyzer as `bird-count` has - check that `Enum`, `List`, `Stream` or list comprehensions aren't used.

Introduction to writing an analyzer extension: https://github.com/exercism/elixir-analyzer/blob/main/docs/writing-an-analyzer.md

An example of an analyzer extension that detect usages of disallowed modules: https://github.com/exercism/elixir-analyzer/pull/50/files#diff-39ba60165e48ed55ff5dc41ce966786ae8f1c83abf1cc3e2430e0b8b5692f105

**Comment by angelikatyborska** [comment]
If you're picking up this issue, please also consider doing https://github.com/exercism/elixir-analyzer/issues/67 as they will most likely be identical analyzers.

**Comment by ThiagosLima** [comment]
If it is ok, I can work on this issue.

**Comment by angelikatyborska** [comment]
That would be great 💜

**Comment by ThiagosLima** [comment]
Maybe the `Simple Linked List` exercise should have an analysis like this 🤔

**Comment by angelikatyborska** [comment]
With the simple-linked-list exercise it's not so straight-forward, because the functions `from_list` and `to_list` can be implemented with `Enum` or `List` functions. Our example solution does that: https://github.com/exercism/elixir/blob/efd211b80aa350e32cf76242f09d12ec4d49df14/exercises/practice/simple-linked-list/.meta/example.ex#L59-L73

**Comment by ThiagosLima** [comment]
I was wondering that because the exercise want us to implement the linked list abstraction. If we use built-in lists abstractions seems strange. Someone could just use `Enum` to implement the exercise. Ex:

```elixir
def reverse(list), do: list |> to_list() |> Enum.reverse() |> from_list()
```

The functions `from_list` and `to_list` could be implemented using recursion. Ex:

```elixir
def from_list([]), do: {}
def from_list([head | tail]), do: {head, from_list(tail)}

def to_list({}), do: []
def to_list({head, tail}), do: [head | to_list(tail)]
```

**Comment by jiegillet** [comment]
Hi @ThiagosLima, since we have not received a PR from you since June, we would like to re-open this issue to other contributors. Of course if you are still working on it, feel free to let us know.

**Comment by angelikatyborska** [comment]
I was mistaken opening this issue because the instructions of this exercise do not mention anywhere that you have to use recursion or that you can't use Enum .
