### ISSUE TITLE
Broken Link on A Guide to Writing an Elixir Analyzer Extension

### ISSUE THREAD

**Issue by ThiagosLima** [exercism/elixir-analyzer#68]
Hi, I was reading [A Guide to Writing an Elixir Analyzer Extension](https://github.com/exercism/elixir-analyzer/blob/main/docs/step-03/step-03.md#3-add-attributes-to-the-matching-process) and I think there is a broken link.

In the **`comment`** part, when I click here I go to an 404 page.

> At this moment, the comments are found in the **exercism/website-copy** repo.

**Comment by angelikatyborska** [comment]
Solved by @neenjaw in https://github.com/exercism/elixir-analyzer/pull/69 🙂. Thank you for reporting!
