### ISSUE TITLE
Write analysis for concept exercise `boutique-inventory`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#81]
Desired checks:
https://github.com/exercism/elixir/blob/9774308bb6b898df6ecbde64c5c6e48c651870ae/exercises/concept/boutique-inventory/.meta/design.md#L31-L36

**Comment by jiegillet** [comment]
This one can be done with existing tools.

**Comment by angelikatyborska** [comment]
This issue has been resolved a while ago in: https://github.com/exercism/elixir-analyzer/pull/194
