### ISSUE TITLE
 Write analysis for concept exercise `dna-encoding`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#84]
Desired checks:
https://github.com/exercism/elixir/blob/9774308bb6b898df6ecbde64c5c6e48c651870ae/exercises/concept/dna-encoding/.meta/design.md#L29-L32

**Comment by jiegillet** [comment]
This can de done using existing tools.

**Comment by julngomz** [comment]
I can work on this issue.

**Comment by jiegillet** [comment]
Hello!
We haven’t seen any PR for this, so feel free to work on it.

**Comment by ryanzidago** [comment]
> Hello! We haven’t seen any PR for this, so feel free to work on it.

I've opened up a PR https://github.com/exercism/elixir-analyzer/pull/242
Let me know what you think :pray:
