### ISSUE TITLE
Write analysis for concept exercise `high-school-sweetheart`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#86]
Desired checks: https://github.com/exercism/elixir/blob/12acf3405242970cd492590e2c9d503330188364/exercises/concept/high-school-sweetheart/.meta/design.md#L31-L37

Note that it's impossible to tell from the AST if the multiline string syntax was used, so we can't do that check.

**Comment by jiegillet** [comment]
Option 5: use the machinery of `mix format`.
```elixir
iex(14)> Code.Formatter.to_algebra!("x = [?a, ?b, ?c]")
{:doc_group,
 {:doc_fits,
  {:doc_cons, {:doc_group, {:doc_string, "x", 1}, :self},
   {:doc_group,
    {:doc_nest,
     {:doc_cons, " =",
      {:doc_cons, {:doc_break, " ", :strict},
       {:doc_group,
        {:doc_fits,
         {:doc_group,
          {:doc_cons,
           {:doc_nest,
            {:doc_cons, "[",
             {:doc_cons, {:doc_break, "", :strict},
              {:doc_cons,
               {:doc_cons, {:doc_group, {:doc_cons, "?a", ","}, :self},
                {:doc_cons, {:doc_break, " ", :strict},
                 {:doc_group, {:doc_cons, "?b", ","}, :self}}},
               {:doc_cons, {:doc_break, " ", :strict},
                {:doc_group, "?c", :self}}}}}, 2, :break},
           {:doc_cons, {:doc_break, "", :strict}, "]"}}, :self}, :enabled},
        :self}}}, 2, :break}, :self}}, :disabled}, :self}
```
I'm not sure exactly how yet, I would need to learn more about it, but it's there for the taking.

**Comment by jiegillet** [comment]
Note to potential contributors: this issue can go ahead ignoring the multiline string issue discussed above, it will require more work and discussion. In the mean time, the other checks can be implemented.
